### ISSUE TITLE
[ANCHORE] Unsolicited random wisdom of the moment

### ISSUE THREAD

**Issue by valancej** [valancej/anchore-notifications#3]
```
details:
  msg: Never pick a fight with people who buy ink by the barrel - Mark Twain
id: 150ea0a2bb5d407c913670e1f2b78cb1
level: info
message: Unsolicited random wisdom of the moment
resource:
  id: null
  type: wisdom
  user_id: admin
source:
  base_url: http://enterprise-notifications:8228
  hostid: anchore-quickstart
  request_id: null
  servicename: notifications
timestamp: '2019-12-04T23:33:01.987114'
type: system.test.random_wisdom
```
